name = "EC880"
uuid = "17931f90-fb53-4c13-bd33-4e3fe38b59dd"
authors = ["Kushal <kushalyspatel@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
